from django.db import models
from taggit.managers import TaggableManager

class Repository(models.Model):
    """
    Stores a single Repository entry, related to a Tag Model and

    The Tag model is auto generated by taggit. Check https://django-taggit.readthedocs.io/en/latest/index.html
    """
    id = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50)
    tags = TaggableManager()