# Generated by Django 2.2.4 on 2019-08-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
    ]
