# Generated by Django 2.2.4 on 2019-08-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='date_searched',
            new_name='search_date',
        ),
    ]
