# Generated by Django 2.2.4 on 2019-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_remove_repository_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='repo-name', max_length=50),
            preserve_default=False,
        ),
    ]
